apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter
  labels:
    app: twitter
  namespace: twitter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitter
  template:
    metadata:
      labels:
        app: twitter
    spec:
      containers:
        - name: app
          image: learnk8s/knote-js:1.0.0
          ports:
            - containerPort: 3000
          env:
          - name: MONGODB_HOSTNAME
            value: mongodb-0.mongodb-headless.database
          - name: MONGODB_PORT
            value: "27017"
          - name: MONGODB_DATABASE
            value: test
          - name: MONGODB_USERNAME
            value: admin
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: creds
                key: db-password