apiVersion: v1
kind: Service
metadata:
  labels:
    app: twitter
  name: twitter-lb
  namespace: twitter
spec:
  ports:
    - name: twitter
      port: 9000
      protocol: TCP
      targetPort: 3000
  selector:
    app: twitter
  type: LoadBalancer
